trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: Default

variables:
  buildConfiguration: Release
  dotnetVersion: 10.0.x
  nodeVersion: 22.x

stages:
- stage: Build_And_Test
  displayName: Build et Tests
  jobs:
  - job: Backend
    displayName: Backend .NET 10
    steps:
    - task: UseDotNet@2
      displayName: Installer .NET 10
      inputs:
        version: $(dotnetVersion)
    - script: dotnet restore Backend/AccessiTrack.slnx
      displayName: Restore NuGet packages
    - script: dotnet build Backend/AccessiTrack.slnx --configuration $(buildConfiguration) --no-restore
      displayName: Build solution
    - script: dotnet publish Backend/AccessiTrack.API --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api
      displayName: Publish API
    - task: PublishBuildArtifacts@1
      displayName: Publier artefact API
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/api
        artifactName: api

  - job: Frontend
    displayName: Frontend Angular
    steps:
    - task: NodeTool@0
      displayName: Installer Node.js
      inputs:
        versionSpec: $(nodeVersion)

    - script: |
        cd Frontend/Accessitrack.client
        call npm install
        call npx ng build --configuration production
      displayName: npm install et ng build
      
    - task: PublishBuildArtifacts@1
      displayName: Publier artefact Frontend
      inputs:
        # On pointe vers le dossier parent 'dist' pour être sûr de tout prendre
        pathToPublish: 'Frontend/Accessitrack.client/dist'
        artifactName: frontend

- stage: Deploy_Production
  displayName: Deploiement Production
  dependsOn: Build_And_Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: accessitrack-secrets
  jobs:
  - deployment: Deploy_API
    displayName: Deployer API sur Azure App Service
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: api

          # AJOUTE LE TEST ICI
          - bash: |
              if [ -z "$(AZURE_WEBAPP_PUBLISH_PROFILE)" ]; then
                echo "##vso[task.logissue type=error]ERREUR : La variable AZURE_WEBAPP_PUBLISH_PROFILE est VIDE ou inaccessible."
                exit 1
              else
                echo "La variable est bien chargée. Longueur : ${#AZURE_WEBAPP_PUBLISH_PROFILE} caractères."
              fi
            displayName: 'Vérifier la variable de secret'
          
          - task: AzureWebApp@1
            displayName: 'Deployer sur accessitrack-api'
            inputs:
              connectionType: 'publishProfile'
              publishProfile: '$(AZURE_WEBAPP_PUBLISH_PROFILE)'
              appType: 'webApp'
              appName: 'accessitrack-api'
              package: '$(Pipeline.Workspace)/api'
              deploymentMethod: 'zipDeploy'
